### ISSUE TITLE
Kitronik product page url not pointing to here

### ISSUE THREAD

**Issue by concretedog** [KitronikLtd/Kitronik-Pico-Simply-Servos-MicroPython#1]
Just tried to navigate to this repo via the product page here https://kitronik.co.uk/products/5339-simply-servos-for-raspberry-pi-pico and the link where the text reads "Github Repo Here" isn't linking correctly to this repo and throwing a 404.

**Comment by JackAtKitronik** [comment]
Thanks for pointing this out to us. We'll get it fixed as soon as possible
